export const HAZARD_CONFIG = {
  // Timings are readable defaults until hazard pacing is tuned.
  laserStrike: {
    telegraphMs: 520,
    activeMs: 240,
    recoverMs: 320,
    width: 28,
    damage: 1,
    blinkMs: 120,
    lineHeight: 6,
    telegraphColor: 0xffd166,
    activeColor: 0xff4d4d,
    recoverColor: 0x7b1e1e,
    beamAlpha: 0.6,
    recoverAlpha: 0.5,
    telegraphDepth: 6,
    beamDepth: 5,
  },
  magnet: {
    telegraphMs: 620,
    activeMs: 260,
    recoverMs: 360,
    width: 180,
    fieldHeight: 120,
    lineHeight: 8,
    blinkMs: 140,
    telegraphColor: 0x7df9ff,
    activeColor: 0x3ddbd9,
    recoverColor: 0x1f6b6a,
    fieldAlpha: 0.35,
    recoverAlpha: 0.45,
    lineDepth: 6,
    fieldDepth: 4,
  },
  scheduling: {
    laserStrikeIntervalMs: 2200,
    laserStrikeInitialDelayMs: 800,
    laserStrikePadding: 60,
    magnetIntervalMs: 3200,
    magnetInitialDelayMs: 1400,
    magnetPadding: 120,
  },
} as const
